src/Entity/MarqueEntity.php
<?php

namespace App\Entity;

use App\Repository\MarqueEntityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MarqueEntityRepository::class)]
class MarqueEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Form/MarqueType.php
<?php

namespace App\Form;

use App\Entity\MarqueEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class MarqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Description')
            ->add('submit' , SubmitType::class, [
                'label' => 'Enregistrer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MarqueEntity::class,
        ]);
    }
}

src/Form/SupprimerMarqueType.php
<?php

namespace App\Form;

use App\Entity\MarqueEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SupprimerMarqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MarqueEntity::class,
        ]);
    }
}

src/Controller/MarqueController.php
<?php

namespace App\Controller;

use App\Form\MarqueType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\MarqueEntity;
use App\Repository\MarqueRepository;
use App\Form\SupprimerMarqueType;


class MarqueController extends AbstractController
{
    #[Route('', name: 'app_marque')]
    public function index(ManagerRegistry $doctrine): Response
    {
        // Récupération des marques depuis le repository
        $repository = $doctrine->getRepository(MarqueEntity::class);
        $marques = $repository->findAll();

        return $this->render('home/index.html.twig', [
            'marques' => $marques, // On passe les marques au template
        ]);
    }
    #[Route('/marque/ajouter', name: 'app_marque_ajout')]
    public function ajouter(Request $request, ManagerRegistry $doctrine): Response
    {
        //Création formulaire
        $marque = new MarqueEntity();
        //Je crée le formulaire
        $form = $this->createForm(MarqueType::class, $marque);

        //Gestion de la requête
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //Sauvegarde de la marque
            $em = $doctrine->getManager();
            $em->persist($marque);
            $em->flush();
            //Redirection vers la page d'accueil
            return $this->redirectToRoute('app_marque');
        }
        return $this->render('marque/ajouter.html.twig', [
            'form' => $form->createView(),
        ]);

    }
    #[Route('/marque/modifier/{id}', name: 'app_marque_modifier')]
    public function modifier($id, Request $request, ManagerRegistry $doctrine, MarqueRepository $repo): Response
    {
        //Création formulaire
        //1 je crée une marque avec doctrine
        $marque =$repo->find($id);
        //2 je crée le formulaire
        $form = $this->createForm(MarqueType::class, $marque);

        //3 gestion de la requête
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //4 je sauvegarde la marque
            $em = $doctrine->getManager();
            $em->persist($marque);
            $em->flush();
            //5 je redirige vers la page d'accueil
            return $this->redirectToRoute('app_marque');
        }

        return $this->render('marque/modifier.html.twig', [
            'controller_name' => 'MarqueController',
        ]);
    }
    #[Route('/marque/supprimer/{id}', name: 'app_marque_supprimer')]
    public function supprimer($id, Request $request, ManagerRegistry $doctrine, MarqueRepository $repo): Response
    {
        //Création formulaire
        //1 je crée une marque avec doctrine
        $marque = $repo->find($id);
        //2 je crée le formulaire
        $form = $this->createForm(SupprimerMarqueType::class, $marque);

        //3 gestion de la requête
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //4 je sauvegarde la marque
            $em = $doctrine->getManager();
            $em->remove($marque);
            $em->flush();
            //5 je redirige vers la page d'accueil
            return $this->redirectToRoute('app_marque');

        }
        return $this->render('marque/supprimer.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/TasseController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class TasseController extends AbstractController
{
    #[Route('/tasse', name: 'app_tasse')]
    public function index(): Response
    {
        return $this->render('tasse/index.html.twig', [
            'controller_name' => 'TasseController',
        ]);
    }

    #[Route('/tasse/ajouter', name: 'app_tasse_ajout')]
    public function ajouter(): Response
    {
        return $this->render('tasse/ajouter.html.twig', [
            'controller_name' => 'TasseController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des marques{% endblock %}
{% block body %}
<h1> Bienvenue </h1>
<table class="table table-stripped">
    {% for m in marques %}
    <tr>
        <td>{{ m.nom }}</td>
        <td>{{ m.description }}</td>
        <td>
            <a href="{{ path('app_marque_modifier', {'id': m.id}) }}" class="btn btn-primary">Modifier</a>
            <a href="{{ path('app_marque_supprimer', {'id': m.id}) }}" class="btn btn-danger">Supprimer</a>
        </td>
    {% endfor %}
    <h2> Ajouter une marque </h2>
    {# Ajout d'un bouton qui redirige vers ajouter.html.twig #}
    <a href="{{ path('app_marque_ajout') }}" class="btn btn-primary">Ajouter une marque</a>
{# {{ form(formulaire)}} #}

    {% endblock %}

templates/marque/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des photos de Chatons{% endblock %}
{% block body %}
    <h1> Bienvenue </h1>
    <h2> Ajouter une marque </h2>
    {{ form(form) }}
{% endblock %}

templates/marque/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une catégorie de chatons{% endblock %}
{% block body %}
    <h1> Bienvenue </h1>
    <h2> Modifier une catégorie </h2>
    {{ form(form) }}
{% endblock %}

templates/marque/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer une catégorie de chatons{% endblock %}
{% block body %}
    <h1> Bienvenue </h1>
    <h2> Supprimer une catégorie </h2>
    {{ form(form)}}
    <h3> Êtes-vous sûr de vouloir supprimer la catégorie</h3>
    <a href="{{ path('app_home') }}" class="btn btn-primary">Annuler</a>
{% endblock %}

templates/tasse/ajoutert.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des photos de Chatons{% endblock %}
{% block body %}
    <h1> Bienvenue </h1>
    <h2> Ajouter une catégorie </h2>
    {{ form(form)}}
{% endblock %}

templates/tasse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TasseController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/home/suiramx/dev/marius_bernard/src/Controller/TasseController.php</code></li>
        <li>Your template at <code>/home/suiramx/dev/marius_bernard/templates/tasse/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}